#!/bin/sh
# this script has been written by Eddy 
#
#		bsnm
#
# Создан 20-го Февраль 2007 года в  0:00
#
EXT=""
if [ -f "$1" ]; then
    EXT=`echo $1|sed 's/.\{1,\}\.//g'`
fi
if [ "$EXT" != "$1" -a "$EXT" != "" ]; then
    echo $1|sed "s/.$EXT//"
else
	echo $1
fi
