#!/bin/sh
# this script has been written by Eddy 
#
#		convcp1251 - конвертирует имена файлов из 1251 в кои8
#
# Создан 05-го Март 2007 года в 13:40
#
#convname-r
#for file in `ls -1`
#do
convmv -f cp1251 -t koi8-r -i --notest -r $*
#done
#echo "Right [Y/N]"?
#read a
#[ "$a" = "Y" -o "$a" = "y" ] && convmv -f UTF-8 -t koi8-r --notest -r $1