#!/bin/sh
# this script has been written by Eddy 
#
#		cpnice -- nisely copies files
#
# Создан 29-го Май 2004 года в 18:55
#

nice -n +20 cp $1 $2 && echo -e "\a\n\n\t\t\aFinished !!!\n"
for a in 1 2 3 4 5
do
    sleep 1
    echo -e "\a\c"
done

for a in 1 2 3 4 5 6 7 8 9 10
do
    usleep 100000
    echo -e "\a\c"
done
