#!/bin/sh
# this script has been written by Eddy 
#
#                mkdatabase -- makes divelist of CD in file DB<number>
#
#
#mount /dev/cdrom
echo -e "\nCreating database\n\tPlease wait\a"
lst=/tmp/CD_DB.$$
cd /Data/CD_Database

listname="DB001"
if [ "$2" != "" ];then
    listname="$2"
else
    cntr=1
    until [ ! -e "$listname" ]
    do
	listname=`echo "DB00$cntr" | sed "s/\(DB\)\(.*\)\([0-9]\{3\}\)/\1\3/"`
	cntr=`expr $cntr + 1`
    done
fi
#[ -e "$listname" ] && \
#    echo -e "\n\nThe CD Database with this name already exists\n\tEnter new name: " && \
#    read listname
list="/Data/CD_Database/$listname"
#list="$listname"

cd $1
#echo "$listname" > $list
ls -1 > "$lst"

while read f
do
    if [ -d "$PWD/$f" ]; then dive -a "$f" | sed "s/\\$1\///g" >> $list
    else echo "$PWD/$f" | sed "s/\\$1\///">> $list
    fi
done<$lst

rm $lst
echo -e "\n\t\tDatabase entry: $listname"
echo -e "\n\tEnter comment:\a"
read comme
echo -e "$listname\t$comme" >> "/Data/CD_Database/Comments"
echo -e "\nDone!!!"
