#!/bin/sh
# this script has been written by Eddy 
#
#		mkdjvu
#
# Создан 05-го Август 2004 года в 13:15
#
#TMPDIR=$PWD/$$
#OLDDIR=$PWD
#mkdir $TMPDIR
#cp $* $TMPDIR
#cd $TMPDIR
echo "Beginning"
for file in `ls -1`
do
    c44 $file
    echo "File $file processed"
done
echo -e "Linking all... \c"
djvm -c book.djview *.djvu
echo "Done!"
rm *.djvu
mv book.djview book.djvu
#mv book.djvu $OLDDIR/book$$.djvu
#cd $OLDDIR
#rm -r $TMPDIR