#!/bin/sh
# this script has been written by Eddy 
#
#		run - запуск команды a la KDE
#
# Создан 12-го Май 2009 года в  9:32
#
COMMAND=`zenity --title="Запуск команды" --text="Что запустить?" --entry`
$COMMAND
